#!/bin/bash
# Auto-generated by agent-contracts. Do not edit manually.
set -uo pipefail

INPUT=$(cat /dev/stdin 2>/dev/null || echo '{}')
COMMAND=$(echo "$INPUT" | jq -r '.command // empty' 2>/dev/null || echo "")

FINAL_EXIT=0

# --- no-force-push (critical / block) ---
if echo "$COMMAND" | grep -qP 'git\s+push\s+.*--force'; then
  echo "BLOCKED: Force push is forbidden per project guardrails" >&2
  FINAL_EXIT=1
fi

# --- no-force-push (critical / block) ---
if echo "$COMMAND" | grep -qP 'git\s+push\s+.*-f\b'; then
  echo "BLOCKED: Force push (-f) is forbidden per project guardrails" >&2
  FINAL_EXIT=1
fi

# --- no-rebase (critical / block) ---
if echo "$COMMAND" | grep -qP 'git\s+rebase'; then
  echo "BLOCKED: Rebase is prohibited; use merge instead" >&2
  FINAL_EXIT=1
fi

# --- english-only-code (warning / warn) ---
if echo "$COMMAND" | grep -qP '[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FFF]'; then
  echo "WARNING: Japanese characters detected in source code" >&2
fi

# --- test-before-commit (mandatory / warn) ---
if echo "$COMMAND" | grep -qP 'git\s+commit'; then
  echo "WARNING: Ensure tests pass before committing" >&2
fi


exit $FINAL_EXIT
